name: UltraCosmetics
author: iSach
version: Beta 1.5
main: me.isach.ultracosmetics.Core
softdepend: [NoteBlockAPI, Vault, LisDisguises]
commands:
  ultracosmetics:
    aliases: [uc, cosmetics]
    description: Main Command of Ultra Cosmetics
    usage: /ultracosmetics