name: UltraCosmetics
author: iSach
version: Beta 1.2.2
main: me.isach.ultracosmetics.Core
softdepend: [NoteBlockAPI]
commands:
  ultracosmetics:
    aliases: [uc, cosmetics]
    description: Main Command of Ultra Cosmetics
    usage: /ultracosmetics