name: UltraCosmetics
author: iSach
version: Beta 1.5.8
load: POSTWORLD
main: me.isach.ultracosmetics.Core
softdepend: [LibsDisguises, NoteBlockAPI, Vault]
commands:
  ultracosmetics:
    aliases: [uc, cosmetics]
    description: Main Command of Ultra Cosmetics
    usage: /ultracosmetics