name: UltraCosmetics
author: iSach
version: Beta 1.6.2
load: POSTWORLD
main: me.isach.ultracosmetics.Core
softdepend: [LibsDisguises, NoteBlockAPI, Vault]
commands:
  canelacosmetics:
    aliases: [uc, cosmetics]
    description: Main Command of Ultra Cosmetics
    usage: /ultracosmetics