# If set to true, it will check at each reload/restart
# if an update is available.
Check-For-Updates: true

# List of the enabled categories.
Categories-Enabled:
  Gadgets: true
  Particle-Effects: true
  Mounts: true
  Pets: true
  Morphs: true
  Hats: true

# Other settings for categories:
# - The Item in Main Menu.
# - Do you want a BackToMainMenu Arrow in it?
Categories:
  Gadgets:
    Main-Menu-Item: '341:0'
    Go-Back-Arrow: true
  Particle-Effects:
    Main-Menu-Item: '362:0'
    Go-Back-Arrow: true
  Mounts:
    Main-Menu-Item: '329:0'
    Go-Back-Arrow: true
  Pets:
    Main-Menu-Item: '383:0'
    Go-Back-Arrow: true
  Morphs:
    Main-Menu-Item: '397:4'
    Go-Back-Arrow: true
  Hats:
    Main-Menu-Item: '310:0'
    Go-Back-Arrow: true

# Treasure Chests Settings.
# /uc reload will not be enough to toggle them!
TreasureChests:

  # Turn to true to toggle on Treasure Chests.
  Enabled: false

  # What is the price of a key?
  Key-Price: 1000

  # Loots settings.
  Loots:
    # Money Loot, even if toggled off, will be given if nothing
    # can be given!
    Money:
      # 'true' for toggled on, 'false' for toggled off.
      Enabled: true
      # The max money a player can get.
      Max: 100
      # chance of getting money.
      Chance: 20
      # Broadcast a message when obtained?
      Message:
        enabled: false
        message: '%prefix% §6§l%name% found %money%$'
    Gadgets-Ammo:
      Enabled: true
      Min: 20
      Max: 100
      Chance: 60
      Message:
        enabled: false
        message: '%prefix% §6§l%name% found %ammo% %gadget% ammo'
    Mounts:
      Enabled: true
      Chance: 10
      Message:
        enabled: false
        message: '%prefix% §6§l%name% found rare %mount%'
    Pets:
      Enabled: true
      Chance: 10
      Message:
        enabled: false
        message: '%prefix% §6§l%name% found rare %pet%'
    Morphs:
      Enabled: true
      Chance: 4
      Message:
        enabled: true
        message: '%prefix% §6§l%name% found legendary %morph%'
    Effects:
      Enabled: true
      Chance: 4
      Message:
        enabled: true
        message: '%prefix% §6§l%name% found legendary %effect%'
    Hats:
      Enabled: true
      Chance: 30
      Message:
        enabled: false
        message: '%prefix% §6§l%name% found rare %hat%'

  # Treasure Chests designs.
  # For a list of effect: http://pastebin.com/CVKkufck
  # For the chest-types: NORMAL or ENDER
  # Material syntax: 'id:data'
  # You CAN make more designs just copy one, paste it and modify.
  # Not twice same name!
  Designs:
    Classic:
      # The block on the center.
      center-block: '169:0'
      # Blocks around the center
      around-center: '5:0'
      # blocks "around around" the center.
      third-blocks: '5:1'
      # Blocks below the chests.
      below-chests: '17:0'
      # The barriers.
      barriers: '85:0'
      # The chest type (NORMAL or ENDER)
      chest-type: NORMAL
      # The effect (complete list: http://pastebin.com/CVKkufck)
      effect: FLAME
    Modern:
      center-block: '169:0'
      around-center: '159:11'
      third-blocks: '155:0'
      below-chests: '159:11'
      barriers: '160:3'
      chest-type: ENDER
      effect: REDSTONE
    Nether:
      center-block: '89:0'
      around-center: '88:0'
      third-blocks: '87:0'
      below-chests: '112:0'
      barriers: '113:0'
      chest-type: NORMAL
      effect: SMOKE_NORMAL
  # Default one is Pex's one.
  # Change it to correspond to your Permissions plugin!
  Permission-Add-Command: pex user %name% add %permission%

# This option will fill the blank slots of inventories
# with a custom item!
Fill-Blank-Slots-With-Item:
  Enabled: false
  Item: '160:15'

# Toggle this to allow players to rename pets.
Pets-Rename:
  Enabled: false
  # If true, the permission:
  # ultracosmetics.pets.rename
  # will be required to rename a pet.
  Permission-Required: false
  # If true, money will be required
  # to rename a pet.
  Requires-Money:
    Enabled: true
    Price: 100

# Do pets drop items? (not pickable up by players)
Pets-Drop-Items: true

# Are pets babies?
Pets-Are-Babies: true

# Do you want the mounts
# that normally make block trails
# to do so?
Mounts-Block-Trails: true

# This option allows to use ammo
# for gadgets, for limited uses.
# Ammo can be given with /uc give ammo
# or bought from menu when activating gadget.
Ammo-System-For-Gadgets:
  Enabled: false
  System: file # file or mysql
  # If system is set to mysql, you must set the infos here.
  MySQL:
    hostname: localhost
    username: root
    password: password
    port: '3306'
    database: UltraCosmetics
# The menu item settings.
Menu-Item:

  # Should it be given on join?
  Give-On-Join: true

  # Should it be given on respawn?
  Give-On-Respawn: true

  # In what slot do you want to give the item?
  Slot: 3

  # What type?
  # Complete list here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  Type: ENDER_CHEST

  # What data?
  Data: 0

  # What display name?
  Displayname: '&6&lCosmetics'

# Settings related to permissions.
No-Permission:

  # Show in lore if player has permission for a cosmetic?
  Show-In-Lore: true

  # Message when a player has permission.
  Lore-Message-Yes: '&o&7Permission: &a&lYes!'

  # Message when player doesn't have a permission.
  Lore-Message-No: '&o&7Permission: &4&lNo!'

  # You want to hide the items the player don't have
  # permission to?
  Dont-Show-Item: false

  # Or show a custom item?
  Custom-Item:
    enabled: false

    # What type?
    # Complete list here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    Type: INK_SACK

    # What data?
    Data: 8

    # What displayname?
    Name: '&c&lNo Permission'
Disabled-Items:

  # When a cosmetic is disabled, want to show it?
  Show-Custom-Disabled-Item: false

  # If you show it, customize the item here.
  Custom-Disabled-Item:

    # What type?
    # Complete list here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    Type: INK_SACK

    # What data?
    Data: 8

    # What displayname?
    Name: '&c&lDisabled'

# If set to true, in messages the cosmetics' names
# won't be colored.
# Example:
# With true: &a&lYou activated &9&lPaintball Gun!
# With false: &a&lYou activated Paintball Gun!
Chat-Cosmetic-PlaceHolder-Color: true

# What is the slot for gadgets?
Gadget-Slot: 4

# If toggled to true,
# players will be able to remove
# their current gadget by pressing
# their drop key.
Remove-Gadget-With-Drop: false

# List of the enabled Worlds